numbers=[5,2,9,1,5,6]
print("original:",numbers)
print("\nFirst:",numbers[0])
print("Second:",numbers[1])
print("Last:",numbers[-1])
print("Third from end :",numbers[-3])
print("\nFrom index 1to before 3:",numbers[1:3])
print("First 3 items:",numbers[:3])
print("From index 3 onwards:",numbers[3])
print("Reversed copy:",numbers[::-1])
numbers.append(3)
print("\nAfter append:",numbers)
numbers.insert(2, 7)
print("After insert:",numbers)
popped =numbers.pop()
print(f"\nPopped last : {popped} |list now:,{numbers}")
popped2=numbers.pop(1)
print(f"\nPopped at index 1 : {popped2} |list now:,{numbers}")
numbers.remove(9)
print(f"\nAfter remove 9: {numbers}")
print(f"\nLength: {len(numbers)}")
print(f"Is 5 present?: {5 in numbers}")
print (f"Index of 6: {numbers.index(6)}")
print(f"Count of 5s: {numbers.count(5)}")
sorted_copy=sorted(numbers)
print(f"\noriginal: {numbers}")
print(f"sorted copy: {sorted_copy}")
numbers.sort
print(f"After .sort: {numbers}")
numbers.reverse()
print(f"After .reverse: {numbers}")
squares = [x**2 for x in numbers]
print(f"\nSquares: {squares}")
evens=[x for x in numbers if x % 2 == 0]
print(f"Evens numbers only: {evens}")